# Generated by Django 4.2.30 on 2026-10-06 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=9, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField()),
            ],
            options={
                'db_table': 'alunos',
                'ordering': ['nome'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_disciplina', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
            ],
            options={
                'db_table': 'disciplinas',
                'ordering': ['nome_disciplina'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('data_matricula', models.DateField()),
                ('nota', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Nota')),
                ('status', models.CharField(blank=True, choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('matriculado', 'Matriculado'), ('cancelado', 'Cancelado')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'matricula',
                'ordering': ['-data_matricula'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=9, null=True)),
                ('data_nascimento', models.DateField()),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'professores',
                'ordering': ['nome'],
                'managed': False,
            },
        ),
    ]
