# Generated by Django 4.2.30 on 2026-04-25 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nota1_nota2_nota3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='nota',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Média'),
        ),
    ]
